// resources/js/Pages/Auth/Login.tsx
import { useForm, Head } from '@inertiajs/react';
import { Radio, Lock, Mail, Loader2 } from 'lucide-react';
import { FormEvent } from 'react';

export default function Login() {
    const { data, setData, post, processing, errors } = useForm({
        email: '',
        password: '',
        remember: false,
    });

    const handleSubmit = (e: FormEvent) => {
        e.preventDefault();
        post('/login');
    };

    return (
        <div className="relative min-h-screen bg-slate-950 text-slate-100 font-sans flex items-center justify-center p-6 overflow-hidden">
            <Head title="Acceder" />

            {/* Background glowing gradients */}
            <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-indigo-500/10 rounded-full blur-3xl" />
            <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-violet-500/10 rounded-full blur-3xl" />

            {/* Login Card Container */}
            <div className="w-full max-w-md relative z-10">
                
                {/* Logo & Header */}
                <div className="flex flex-col items-center mb-8 text-center">
                    <div className="p-3 bg-gradient-to-br from-indigo-500 to-violet-600 rounded-2xl shadow-xl shadow-indigo-500/20 mb-4 animate-pulse">
                        <Radio className="w-6 h-6 text-white" />
                    </div>
                    <h2 className="text-3xl font-extrabold tracking-tight bg-gradient-to-r from-white to-slate-400 bg-clip-text text-transparent">
                        TuiStream Panel
                    </h2>
                    <p className="mt-2 text-sm text-slate-400">
                        Ingresa tus credenciales para acceder a tus emisoras
                    </p>
                </div>

                {/* Glassmorphic Form Card */}
                <div className="bg-slate-900/45 border border-slate-800/80 backdrop-blur-md rounded-2xl p-8 shadow-2xl">
                    <form onSubmit={handleSubmit} className="space-y-6">
                        
                        {/* Email Input */}
                        <div>
                            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">
                                Correo Electrónico
                            </label>
                            <div className="relative">
                                <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                                    <Mail className="w-4 h-4" />
                                </span>
                                <input
                                    type="email"
                                    required
                                    value={data.email}
                                    onChange={(e) => setData('email', e.target.value)}
                                    placeholder="correo@ejemplo.com"
                                    className="w-full bg-slate-950 border border-slate-850 focus:border-indigo-500 rounded-xl py-3 pl-10 pr-4 text-sm text-slate-200 placeholder-slate-650 focus:ring-1 focus:ring-indigo-500 transition-all outline-none"
                                />
                            </div>
                            {errors.email && (
                                <p className="mt-2 text-xs text-red-400 font-medium">{errors.email}</p>
                            )}
                        </div>

                        {/* Password Input */}
                        <div>
                            <div className="flex justify-between items-center mb-2">
                                <label className="block text-xs font-semibold uppercase tracking-wider text-slate-400">
                                    Contraseña
                                </label>
                                <a href="#forgot" className="text-xs text-indigo-400 hover:text-indigo-300 transition-colors">
                                    ¿Olvidaste tu contraseña?
                                </a>
                            </div>
                            <div className="relative">
                                <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-500">
                                    <Lock className="w-4 h-4" />
                                </span>
                                <input
                                    type="password"
                                    required
                                    value={data.password}
                                    onChange={(e) => setData('password', e.target.value)}
                                    placeholder="••••••••"
                                    className="w-full bg-slate-950 border border-slate-850 focus:border-indigo-500 rounded-xl py-3 pl-10 pr-4 text-sm text-slate-200 placeholder-slate-650 focus:ring-1 focus:ring-indigo-500 transition-all outline-none"
                                />
                            </div>
                            {errors.password && (
                                <p className="mt-2 text-xs text-red-400 font-medium">{errors.password}</p>
                            )}
                        </div>

                        {/* Remember Me Checkbox */}
                        <div className="flex items-center">
                            <input
                                id="remember-me"
                                type="checkbox"
                                checked={data.remember}
                                onChange={(e) => setData('remember', e.target.checked)}
                                className="w-4 h-4 text-indigo-600 bg-slate-950 border-slate-850 rounded focus:ring-indigo-500 focus:ring-offset-slate-950"
                            />
                            <label htmlFor="remember-me" className="ml-2 text-sm text-slate-400 select-none">
                                Recordar sesión
                            </label>
                        </div>

                        {/* Submit Button */}
                        <button
                            type="submit"
                            disabled={processing}
                            className="w-full py-3.5 px-4 bg-gradient-to-br from-indigo-500 to-violet-600 hover:from-indigo-600 hover:to-violet-700 disabled:opacity-50 text-white font-medium rounded-xl shadow-lg shadow-indigo-500/20 hover:shadow-indigo-500/30 transition-all flex items-center justify-center gap-2 transform hover:-translate-y-0.5"
                        >
                            {processing ? (
                                <>
                                    <Loader2 className="w-4 h-4 animate-spin" /> Accediendo...
                                </>
                            ) : (
                                'Iniciar Sesión'
                            )}
                        </button>

                    </form>
                </div>

                {/* Footer Credits */}
                <p className="mt-8 text-center text-xs text-slate-500">
                    &copy; 2026 TuiStream. Todos los derechos reservados.
                </p>
            </div>
        </div>
    );
}

// resources/js/Pages/Auth/Login.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useForm, Link } from '@inertiajs/vue3';
import GuestLayout from '@/Layouts/GuestLayout.vue';

const form = useForm({
    email: '',
    password: '',
    remember: false,
});

const showPassword = ref(false);
const loginError = ref('');

function submit() {
    loginError.value = '';

    form.post('/login', {
        preserveScroll: true,
        onError: (errors) => {
            loginError.value = errors.email || 'Error al iniciar sesión. Verifica tus credenciales.';
        },
        onFinish: () => {
            form.reset('password');
        },
    });
}
</script>

<template>
    <GuestLayout>
        <div class="p-6 sm:p-8">
            <!-- Header -->
            <div class="text-center mb-8">
                <h2 class="text-xl font-bold text-gray-900 dark:text-white">Iniciar Sesión</h2>
                <p class="text-sm text-gray-500 dark:text-gray-400 mt-1.5">Accede al panel de administración de TuiStream</p>
            </div>

            <!-- Error Alert -->
            <div v-if="loginError" class="alert alert-error mb-4">
                <svg class="w-4 h-4 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                {{ loginError }}
            </div>

            <!-- Form -->
            <form @submit.prevent="submit" class="space-y-4">
                <div>
                    <label for="email" class="label">Correo electrónico</label>
                    <input
                        id="email"
                        v-model="form.email"
                        type="email"
                        class="input-field"
                        placeholder="info@hostuis.com"
                        required
                        autocomplete="email"
                        autofocus
                    />
                </div>

                <div>
                    <label for="password" class="label mb-1.5">Contraseña</label>
                    <div class="relative">
                        <input
                            id="password"
                            v-model="form.password"
                            :type="showPassword ? 'text' : 'password'"
                            class="input-field pr-12"
                            placeholder="••••••••"
                            required
                            autocomplete="current-password"
                        />
                        <button
                            type="button"
                            @click="showPassword = !showPassword"
                            class="absolute right-3 top-1/2 -translate-y-1/2 p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-400 transition-colors"
                            :aria-label="showPassword ? 'Ocultar contraseña' : 'Mostrar contraseña'"
                        >
                            <svg v-if="showPassword" class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                            </svg>
                            <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                <path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                            </svg>
                        </button>
                    </div>
                </div>

                <div class="flex items-center gap-3">
                    <label class="relative inline-flex items-center cursor-pointer select-none">
                        <input v-model="form.remember" type="checkbox" class="sr-only peer" />
                        <div class="w-9 h-5 bg-gray-200 dark:bg-gray-700 peer-focus:ring-2 peer-focus:ring-tuistream-500 rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-tuistream-600 transition-colors"></div>
                        <span class="ms-2 text-xs text-gray-600 dark:text-gray-400">Recordarme</span>
                    </label>
                </div>

                <button
                    type="submit"
                    :disabled="form.processing"
                    class="btn-primary w-full justify-center mt-2"
                >
                    <svg v-if="form.processing" class="w-4 h-4 animate-spin" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                    {{ form.processing ? 'Iniciando sesión...' : 'Iniciar Sesión' }}
                </button>
            </form>

            <!-- Footer -->
            <div class="mt-6 p-4 bg-gray-50 dark:bg-gray-800/50 rounded-xl border border-gray-100 dark:border-gray-700">
                <p class="text-xs text-gray-500 dark:text-gray-400 text-center">
                    <svg class="w-3.5 h-3.5 inline-block mr-1 text-tuistream-500" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                    </svg>
                    Solo el administrador del sistema puede crear nuevas cuentas de usuario.
                </p>
            </div>
        </div>
    </GuestLayout>
</template>
